<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolSystem.Repository\SchoolSystem.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validators\ClassroomValidator\" />
    <Folder Include="Validators\StudentValidator\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

</Project>
